### ISSUE TITLE
how to wp_enqueue_style

### ISSUE THREAD

**Issue by Ferossgp** [roborourke/wp-sass#16]
How wp_enqueue_style for style.scss.php ?
i tried this : 

<pre>
wp_enqueue_style( 
                'admin', 
                get_stylesheet_directory_uri() . '/scss/style.scss.php',
                array(),
            THEME_VERSION
            );
</pre>

but i get error.

Thanks

**Comment by Ferossgp** [comment]
i get this eror

<pre>
Number must be a number: C:\wamp\www\wordpress/wp-content/uploads/wp-sass-cache/admin.css.cache.preprocessed.scss::24 Source: (HERE IS MY CSS)
</pre>

**Comment by ankitsingh101** [comment]
Did you solved your issue?
