### ISSUE TITLE
@extend .class with &:after and &:before code not producing expected output?

### ISSUE THREAD

**Issue by ericpedia** [roborourke/wp-sass#5]
Not sure if this is a phpsass issue or a wp-sass issue (or if I'm somehow misapplying \@extend):

SCSS:

```
.clearfix {
    &:before, &:after {
        content: ""
        display: table
    }
    &:after {
      clear: both
      }
    zoom: 1
}

.myclass {
     ul {
        li {
            @extend .clearfix;
        }
    }
}
```

Resulting CSS:

```
.clearfix,
.myclass ul li {
  zoom: 1; }
  .clearfix:before,
  .clearfix:after,
  .myclass ul li {
    content: "" display: table; }
  .clearfix:after,
  .myclass ul li {
    clear: both; }
```

Note that the :before and :after properties is getting added not to `.myclass ul li:before` and  `.myclass ul li:after`, but directly to `.myclass ul li`.

**Comment by noeltock** [comment]
The first thing I always do with things like this is check issues from the original repo, sometimes helps save time.

**Comment by ericpedia** [comment]
Right, I didn't find it there; should I assume any SASS-to-CSS output issue is a PHPSASS issue and not WPSASS?

**Comment by noeltock** [comment]
This might be the issue (or part of it)?

https://github.com/richthegeek/phpsass/issues/13

**Comment by roborourke** [comment]
I think so yeah. Wp-sass is just a Wordpress wrapper for that package so if there's a problem with wp bugs or plugin/theme conflicts etc...  let me know :)

**Comment by ericpedia** [comment]
FYI the relevant PHPSass issue is this one: https://github.com/richthegeek/phpsass/issues/45
